# Generated by Django 4.0.4 on 2022-07-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Publicado/No publicado'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='titulo',
            field=models.CharField(max_length=40, verbose_name='titulo'),
        ),
    ]
